#include "HCNetSDK.h"
char *StructName[] = {"NET_DVR_ALRAM_FIXED_HEADER", "NET_DVR_GET_STREAM_UNION", "NET_DVR_STREAM_MODE", "NET_DVR_IPPARACFG_V40",  };  
 DWORD dwStructSize[] = {sizeof(NET_DVR_ALRAM_FIXED_HEADER), sizeof(NET_DVR_GET_STREAM_UNION), sizeof(NET_DVR_STREAM_MODE), sizeof(NET_DVR_IPPARACFG_V40),  }; 