#include "HCNetSDK.h"
char *StructName[] = {"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "", "", "", "",\
	"", "", "", "", "", "", "",  };  
 DWORD dwStructSize[] = {sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),
	 sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(), sizeof(),  }; 